import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/app/components/NavBar.tsx";
import { FooterData } from "./utils/sidebarData";
import Link from "next/link";
import Image from "next/image";
import Logo from "../public/assets/nippyLogo.svg";
import AlertNotifications from "./components/Alert/AlertNotifications";
import SideMenu from "./components/SideMenu";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/assets/logoIcon.svg" />
      <body className={``}>
        <div className="h-[8vh] sm:h-[5vh] xl:h-[10vh] flex  items-center justify-center">
          <Navbar />
        </div>
        <div className="border-t border-gray-300 h-[92vh] sm:h-[95vh] lg:h-[90vh] md:flex ">
          <div className="w-1/4 h-full sticky top-0 overflow-y-auto hidden md:block  ">
            <SideMenu />
          </div>
          <div className="w-full md:w-2/4 border-r  border-l border-gray-300  h-full overflow-y-auto scrollbar-hide">
            {children}

            <footer className="bg-[#FFF0F0] py-6 px-10">
              <Link href="/">
                <Image
                  src={Logo}
                  alt="Nippy Logo"
                  width={128}
                  height={36}
                  className="w-48 md:w-60 h-auto"
                />
              </Link>

              <ul className="mt-8">
                {FooterData.map((item, idx) => {
                  return (
                    <li key={idx * 2} className="text-[#444746] my-4">
                      <Link href="/" className="">
                        {item.title}
                      </Link>
                    </li>
                  );
                })}
              </ul>
              <p className="text-[#444746] mt-2">
                {" "}
                &copy; Copyrigth 2024, All right reserved.
              </p>
            </footer>
          </div>
          <div className="w-1/4 h-full overflow-y-auto hidden md:block px-6">
            <AlertNotifications />
          </div>
        </div>
      </body>
    </html>
  );
}
